<?php
if(basename($_SERVER["PHP_SELF"])==basename(__FILE__)){
exit("<script>alert('Nè´™o Permitido')</script>\n<script>window.location=('/')</script>");
}
if(isset($_COOKIE['ocimg'])==false){  
$colors = array('#000000');  
$colortop = array('#ffffff'); 
$colortop1 = array('black'); 
$colorred = array('##FF0000');
$imgmusica='<i class="ion-volume-high" style="font-size:50px;font-weight: bold;color:'.$colorred[array_rand($colorred)].'"></i>&nbsp;';
$imgmp4='<i class="ion-videocamera" style="font-size:50px;font-weight: bold;color:'.$colorred[array_rand($colorred)].'"></i>&nbsp;';
$imgenviada='<i class="ion-camera" style="font-size:50px;font-weight: bold;color:'.$colorred[array_rand($colorred)].'"></i>&nbsp;';
$imgjogos='<i class="ion-ios-game-controller-b" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgmensagem='<i class="ion-email-unread" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgprivado='<i class="ion-locked" style="font-size:26px;font-weight: bold;color:'.$colortop1[array_rand($colortop1)].'"></i>&nbsp;';
$imgmnot='<i class="ion-android-notifications" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgonline='<i class="ion-ios-people" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgradio='<i class="ion-music-note" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgpreferencias='<i class="ion-android-settings" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imga1='<i
class="ion-android-person-add" style="font-size:22px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i>&nbsp;';
$imgamigos='<i class="ion-android-person-add" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsairsla='<i class="ion-android-exit" style="font-size:25px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgyoutube='<i class="ion-social-youtube" style="font-size:2px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsalas='<i class="ion-chatboxes" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgposts='<i class="ion-chatbubbles" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsmilies='<i class="ion-android-happy" style="font-size:14px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgbolinha='<i class="ion-android-boat" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgup='<img src="/noticias_icons/up.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imglibertadores='<img src="/noticias/libertadores.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgfum='<img src="/style/f1.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgdado='<i class="ion-android-apps" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imginformacao='<i class="ion-information-circled" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgdiversos='<i class="ion-android-options" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgparceiros='<i class="ion-ios-body" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgseta='<i class="ion-ios-redo" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsetavoltar='<i class="ion-ios-undo" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsaldacao='<i class="ion-android-add-circle" style="font-size:20px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcdc='<i class="ion-trophy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgfazenda='<i class="ion-ios-rose" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgloteria='<i class="ion-share" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgblog='<i class="ion-ios-book" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgpouc='<i class="ion-flag" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcorrida='<i class="ion-android-car" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgppt='<i class="ion-ios-pint" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgtime='<i class="ion-ios-baseball" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgemail='<img src="/style/email.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgforca='<i class="ion-android-sad" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgclaro='<img src="/style/claro.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgbanco='<i class="ion-cash" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgconcursos='<img src="/style/concursos.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgcalc='<i class="ion-ios-calculator" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgwapet='<i class="ion-social-tux" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgnovelas='<img src="/style/novelas.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgcassino='<i class="ion-social-apple" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgbolo='<i class="ion-android-hangout" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgajuda='<i class="ion-help-buoy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgparouimpar='<i class="ion-android-hand" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcp='<img src="/style/cp.jpg" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgmsn='<img src="/style/msn.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imginicio='<i class="ion-ios-home" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgatualizar='<i class="ion-android-refresh" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsegredos ='<i class="ion-help-circled" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgok='<i class="ion-checkmark" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgerro='<i class="ion-bug" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgfrases='<img src="/style/frasesms.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgaddfrase='<img src="/style/addfrase.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgcorreio='<i class="ion-android-mail" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcorreio2='<img src="/style/notificacao.png" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgemo='<i class="ion-android-happy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$cemo='<i class="ion-android-happy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcorreiov='<i class="ion-ios-contact-outline" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgrecados='<i class="ion-android-textsms" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgyoutube='<i class="ion-social-youtube" style="font-size:25px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgchat='<img src="/style/chat.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgservicos='<i class="ion-leaf" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcomunidades='<i class="ion-ios-people" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgforum='<i class="ion-chatboxes" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgbatepapo='<i class="ion-ios-chatbubble" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgalbuns='<i class="ion-images" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgdownloads='<i class="ion-ios-cloud-download" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgconcurso='<img src="/style/concurso.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgestatisticas='<i class="ion-stats-bars" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsair='<i class="ion-log-out" style="font-size:25px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgimagens='<i class="ion-ios-photos" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgfotos='<i class="ion-android-color-palette" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgsons='<i class="ion-ios-musical-notes" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgvideos='<i class="ion-ios-videocam" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgbusca='<i class="ion-android-search" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgusuarios='<img src="/style/usuarios.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgmasc='<i class="ion-man" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgfem='<i class="ion-woman" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgniver='<i class="ion-android-happy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgextra='<i class="ion-settings" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgdiversao='<i class="ion-ios-game-controller-b-outline" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgquente='<img src="/style/quente.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgmovido='<img src="/style/movido.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgmoedas='<i class="ion-social-usd" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgtrancado='<img src="/style/trancado.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgenquete='<i class="ion-ribbon-a" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcomentar='<img src="/style/comentar.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imglogo='<img src="/style/logo.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imganuncios='<img src="/style/anuncios.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgon='<i class="ion-person-stalker" style="font-size:22px;font-weight: bold;color:#00FF7F"></i>&nbsp;';
$imgoff='<i class="ion-android-alarm-clock" style="font-size:22px;font-weight: bold;color:#DC143C"></i>&nbsp;';
$imgocp='<i class="ion-android-person" style="font-size:22px;font-weight: bold;color:#FF8C00"></i>&nbsp;';
$imgmarcada='<img src="/style/marcada.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imglida='<i class="ion-android-drafts" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgnaolida='<i class="ion-android-mail" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgjava='<img src="/style/java.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgsymbian='<img src="/style/symbian.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgbgf='<img src="/style/bgf.png" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgavbom='<i class="ion-thumbsup" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgavruim='<i class="ion-thumbsdown" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgtop10='<i class="ion-star" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgcmt='<img src="/style/imgcmt.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgnoticias='<i class="ion-social-designernews" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgadd='<i class="ion-android-add-circle" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgquiz='<i class="ion-help-circled" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgdir='<img src="/style/dir.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgpedidos='<i class="ion-social-buffer" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgloja='<i class="ion-android-cart" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgzip='<img src="/style/zip.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgswf='<img src="/style/swf.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgandroid='<i class="ion-social-android" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgporno='<i class="ion-android-navigate" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgpesca='<i class="ion-code" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgleilao='<i class="ion-android-bulb" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgpombo='<i class="ion-social-twitter" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgpokemon='<i class="ion-social-reddit" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgzumbi='<i class="ion-social-snapchat" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imghipod='<i class="ion-trophy" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgbote='<i class="ion-beer" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imggato='<i class="ion-social-octocat" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$imgtempo='<i class="ion-ios-time" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>&nbsp;';
$mensa='<a href="/mensagens/entrada" style="padding:7px 0;"><i class="ion-android-mail" style="font-size:23px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i></a>';
$notif='<a href="/mensagens/coletiva" style="padding:7px 0;"><i class="ion-earth" style="font-size:23px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i></a>';
$conf='<a href="/configuracoes" style="padding:7px 0;"><i class="ion-android-settings" style="font-size:25px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i></a>';
$amigo='<a href="/amigos" style="padding:7px 0;"><i class="ion-person-stalker" style="font-size:23px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i></a>';
$amigos='<a href="/amigos/pedidos" style="padding:7px 0;"><i class="ion-person-stalker" style="font-size:23px;font-weight: bold;color:'.$colortop[array_rand($colortop)].'"></i></a>';
$acc='<i class="ion-ios-heart" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>';
$dicas='<i class="ion-android-clipboard" style="font-size:22px;font-weight: bold;color:'.$colors[array_rand($colors)].'"></i>';
}else{	
$acc='<img src="/style/bbb.gif" style="width:20px;height:20px;display:inline-block">';
$cemo='<img src="/style/emocoes.gif" style="width:20px;height:20px;display:inline-block">';
$dicas='<img src="/style/bbcode.gif" style="width:20px;height:20px;display:inline-block">';
$imgsaldacao='';
$imgbatepapo='';
$imgbolinha='';
$imgup='';
$imglibertadores='';
$imgfum='';
$imgdado='';
$imginformacao='';
$imgdiversos='';
$imgparceiros='';
$imgseta='';
$imgsetavoltar='';
$imgcdc='';
$imgfazenda='';
$imgloteria='';
$imgblog='';
$imgpouc='';
$imgcorrida='';
$imgppt='';
$imgtime='';
$imgemail='';
$imgforca='';
$imgclaro='';
$imgbanco='';
$imgconcursos='';
$imgcalc='';
$imgwapet='';
$imgnovelas='';
$imgcassino='';
$imgbolo='';
$imgajuda='';
$imgparouimpar='';
$imgcp='';
$imgmsn='';
$imginicio='';
$imgatualizar='<img src="/style/atualizar.png" style="width:20px;height:20px;display:inline-block">';
$imgsegredos ='';
$imgok='';
$imgerro='';
$imgfrases='';
$imgaddfrase='';
$imgcorreio='';
$imgcorreio2='';
$imgemo='';
$imgcorreiov='';
$imgrecados='';
$imgyoutube='';
$imgchat='';
$imgservicos='';
$imgcomunidades='';
$imgforum='';
$imgamigos='';
$imgalbuns='';
$imgdownloads='';
$imgpreferencias='';
$imgconcurso='';
$imgestatisticas='';
$imgsair='';
$imgimagens='';
$imgfotos='';
$imgsons='';
$imgvideos='';
$imgbusca='';
$imgusuarios='';
$imgmasc='';
$imgfem='';
$imgniver='';
$imgfem='';
$imgextra='';
$imgdiversao='';
$imgquente='';
$imgmovido='';
$imgmoedas='';
$imgtrancado='';
$imgenquete='';
$imgcomentar='';
$imglogo='';
$imganuncios='';
$imgon='<img src="/style/online.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgoff='<img src="/style/offline.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgocp='<img src="/style/ocupado.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgmarcada='';
$imglida='<img src="/style/lida.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgnaolida='<img src="/style/naolida.gif" style="width:20px;height:20px;display:inline-block">&nbsp;';
$imgjava='';
$imgsymbian='';
$imgbgf='';
$imgavbom='';
$imgavruim='';
$imgtop10='';
$imgcmt='';
$imgnoticias='';
$imgadd='';
$imgquiz='';
$imgdir='';
$imgtemas='';
$imgpedidos='';
$imgloja='';
$imgzip='';
$imgswf='';
$imgandroid='';
$imgporno='';
$imgpesca='';
$imgleilao='';
$imgpombo='';
$imgpokemon='';
$imgzumbi='';
$imghipod='';
$imgbote='';
$imggato='';
$imgtempo='';    
}
?>